export const TYPES = {
  UPDATE_POST: 'UPDATE_POST',
  EDIT_POST: 'EDIT_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  ADD_POST: 'ADD_POST',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  DELETE_POST: 'DELETE_POST',
} as const;

