export const TYPES = {
  TOGGLE_THEME: 'TOGGLE_THEME',
  EDIT_FEEDBACK: 'EDIT_FEEDBACK',
  IS_LOADING: 'IS_LOADING',
  UPDATE_FEEDBACK: 'UPDATE_FEEDBACK',
  ADD_FEEDBACK: 'ADD_FEEDBACK',
  FETCH_FEEDBACK: 'FETCH_FEEDBACK',
  IS_ERROR: 'IS_ERROR',
  DELETE_FEEDBACK: 'DELETE_FEEDBACK',
} as const;

export const BASE_URL: string = 'https://63d58a4d94e769375ba4cc65.mockapi.io/feedback/';
