export const TYPES = {
  DECREASE: 'DECREASE',
  INCREASE: 'INCREASE',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  TOTAL_AMOUNT: 'TOTAL_AMOUNT',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
} as const;
